### ISSUE TITLE
Autocomplete in RStudio

### ISSUE THREAD

**Issue by amanxng** [burgerga/shinyTime#5]
Not sure if there is something additional I need to do to set it up but ShinyTime control's id does not show up in autocomplete.

For example if there are two controls: myDate (shiny::dateInput) and myTime (ShinyTime) then upon writing "input$" in server.R, the only prompt I see is for myDate.

**Comment by burgerga** [comment]
Hmm, I didn't even know that should have worked. After some digging around I found the responsible code in https://github.com/rstudio/rstudio/blob/master/src/cpp/session/modules/SessionRCompletions.R#L2688 but no clue why it doesn't work (`timeInput` ends with `Input` so it should be picked up...). 
I'm also guessing that this will take quite some time since it involves building and debugging rstudio, so I'm saying up front that fixing this will not be a priority for me, however, I'll take a closer look at it ;)

**Comment by burgerga** [comment]
Ah this is simply not released (https://github.com/rstudio/rstudio/commit/0813e60f2857c3a100e4e2cfa8316e82b26996cb) so it will start to work in a later RStudio version!

**Comment by amanxng** [comment]
Thanks for the investigation mate!
Good that this will work in a latter version of RStudio...
